### DISCUSSION TITLE
Dynamic project URL or dynamic project name in the "issue_format"

### DISCUSSION THREAD

**Discussion by simon-liebehenschel** [twisted/towncrier#465] [Ideas]
I have dozens of Git repositories and I share all tools config files via a single Git submodule. 

Any config file must be repository-agnostic. I mean that there must not be hard-coded repositories names, hard-coded URLs, etc.

How can I achieve something like:

```toml
[tool.towncrier]
issue_format = "[#{issue}]({$PROJECT_URL}/-/issues/{issue})"
```
where `$PROJECT_URL` is (obviously) a URL of a project.

Or, as an alternative, how can I inject a project name into a URL:

```toml
[tool.towncrier]
project_name = "something"
issue_format = "[#{issue}](https://gitlab.com/organization/{PROJECT_NAME}/-/issues/{issue})"
```
?
