### DISCUSSION TITLE
start_string issue

### DISCUSSION THREAD

**Discussion by Snipy7374** [twisted/towncrier#478] [Q&A] [answered]
towncrier won't recognize the `start_string`

```toml
[tool.towncrier]
package = "nasa"
directory = "changelogs/"
filename = "docs/source/whats_new.rst"
issue_format = ":issue:`{issue}`"
underlines = "-~"
```
that's how i configured it; then in my changelog file i do

```rst
Chanegelog
==========

test

.. towncrier release notes start
```
but that's not working, towncrier is ignoring the start line

I'm using the latest version of towncrier, 22.12.0
