### DISCUSSION TITLE
Ability to set different fragment types

### DISCUSSION THREAD

**Discussion by OnceUponALoop** [twisted/towncrier#707] [General]
In our use-case we found it helpful to extend the existing categories (to match our conventional commit categories) and support multiple fragment extensions for each category.

This was accomplished from the outside by adding the logic to the jinja template (macro abuse) rather than modifying towncrier source.
I'm wondering if this is a common enough use-case that it would be worth extending to cover in towncrier directly.

## Example

| Type | Extension(s) |
| --- | --- |
| 🚀 Feature | `.feat`, `.feature` |
| 🐞 Bug | `.bug`, `.bugfix`, `.fix` | 
| ✔️ Minor Changes | `.minor`, `.refactor` |
| 🌀 Miscellaneous | `.misc`, `.chore` |

`towncrier.toml` snippet

```toml
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                           🏷️ Category Definitions                           ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# ─── 🚀 Features ───────────────────────────────────────────────────────────────
#
# Fragment: [ feat | feature ]

[[tool.towncrier.type]]
name="🚀 Features"
directory="feat"
showcontent=true

[[tool.towncrier.type]]
name="🚀 Features"
directory="feature"
showcontent=true

# ─── 🐞 Bugfixes ───────────────────────────────────────────────────────────────
#
# Fragment: [ fix | bugfix | bug ]

[[tool.towncrier.type]]
name="🐞 Bugfixes"
directory="bugfix"
showcontent=true

[[tool.towncrier.type]]
name="🐞 Bugfixes"
directory="fix"
showcontent=true

[[tool.towncrier.type]]
name="🐞 Bugfixes"
directory="bug"
showcontent=true
```
