### ISSUE TITLE
Towncrier stopped to render a title in version 21.3.0

### ISSUE THREAD

**Issue by YevheniiSemendiak** [twisted/towncrier#340]
Hey there! After installing the latest Towncrier version, it stopped generating a release title (simply proceeding with the release details):
![image](https://user-images.githubusercontent.com/32543098/114440289-9dee2700-9bd2-11eb-952f-a960633e718b.png)

The config file is following:

```toml
[tool.towncrier]
    directory = "CHANGELOG.D"
    filename = "CHANGELOG.md"
    template = "CHANGELOG.D/towncrier_template.md"
    issue_format = "[#{issue}](https://github.com/neuro-inc/cookiecutter-neuro-project/issues/{issue})"
    start_string = "[comment]: # (towncrier release notes start)\n"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false
```
