### ISSUE TITLE
Top line is applied twice

### ISSUE THREAD

**Issue by kasium** [twisted/towncrier#352]
Hi,
with the latest version of towncrier the top line is twice applied leading to a weird text and invalid rST.

__pyproject.toml__
```toml
[tool.towncrier]
filename = "CHANGELOG.rst"
directory = "news/"
title_format = "{version} ({project_date})"

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true
```

__news/123.feature__
```rst
dummy
```
__CHANGELOG.rst__
```rst
.. towncrier release notes start
```

If I now execute `towncrier --yes  --version 0.50.0`, teh following text is generated:

__CHANGELOG.rst__
```rst
0.50.0 (2021-06-28)0.50.0 (2021-06-28)
===================

Features
--------

- dummy (#1234)


.. towncrier release notes start
```
