### ISSUE TITLE
Support nested sections

### ISSUE THREAD

**Issue by kasium** [twisted/towncrier#490]
Let's imagine the following project X:

- frontend
  - fixed
  - features
- backend
  - fixed
  - features

Currently in towncrier you would need 4 fragments with their configuration in TOML. However, it would be a great feature if towncrier would support something like

```toml
[tool.towncrier]
package = "X"

  [[tool.towncrier.category]]
  directory = "backend"
  name = "Backend"

    [[tool.towncrier.type]]
    directory = "feature"
    name = "Features"
    showcontent = true
```

With that, given a file `foo.backend.feature` would render similar to

```rst
Backend
--------

Features
^^^^^^^^

* My feature (foo)
```
