### ISSUE TITLE
pre-commit autoupdate seems to fail

### ISSUE THREAD

**Issue by HealthyPear** [twisted/towncrier#571]
When I launch pre-commit autoupdate I get this

```
$ pre-commit autoupdate
[https://github.com/pre-commit/pre-commit-hooks] already up to date!
[https://github.com/psf/black-pre-commit-mirror] already up to date!
[https://github.com/adamchainz/blacken-docs] already up to date!
[https://github.com/rstcheck/rstcheck] already up to date!
[https://github.com/charliermarsh/ruff-pre-commit] already up to date!
[https://github.com/nbQA-dev/nbQA] already up to date!
[https://github.com/twisted/towncrier]
=====> /var/folders/2z/142033n17rbfy969s6h4hymw0000gn/T/tmphs0r_674/.pre-commit-hooks.yaml is not a file
```

So all other git hooks get updated, but it crashes only when trying to update this project.

I also tried to manually update the config file with what I see from your docs,

```yaml
  - repo: https://github.com/twisted/towncrier
    rev: 22.13.0
    hooks:
      - id: towncrier-check
```

but the result doesn't change.

Also `pre-commit clean` doesn't seem to help.

**Comment by adiroiban** [comment]
Thanks for the report

I see that pre-commit support was added here https://github.com/twisted/towncrier/pull/499

I am not very familiar with pre-commit internals.

Can you please provide a self contained example so that I can reproduce this error?

**Comment by HealthyPear** [comment]
I think the minimal example is to use what it proposed in the docs, so a `.pre-commit-config` file with just

```
  - repo: https://github.com/twisted/towncrier
    rev: 22.13.0
    hooks:
      - id: towncrier-check
```
