### ISSUE TITLE
🐛 Bug - Missing underline character for emojis

### ISSUE THREAD

**Issue by jacobgulan** [twisted/towncrier#626]
Whenever running the `towncrier` command for my release notes, the changelog.rst file that's generated for it is missing an underline for every emoji character that's used.

pyproject.toml setting looks as such:

```TOML
[tool.towncrier]
directory = "CHANGES"
filename = "CHANGELOG.rst"
package = "mypackage"
title_format = "mypackage v{version} ({project_date})"
underlines = ["-", "~", "^"]

    [[tool.towncrier.type]]
    directory = "bugfix"
    name = "🐛 Bugfixes"
    showcontent = true
```

changelog.rst looks as such:

```rst

🐛 Bugfixes
~~~~~~~~~~
```
