### ISSUE TITLE
Default `name` should refer to pyproject.toml.project.name

### ISSUE THREAD

**Issue by zerothi** [twisted/towncrier#685]
This applies to the `pyproject.toml` integration.

The `tool.towncrier.package` field defaults to `""`. However, when towncrier is defined in a `pyproject.toml` file, wouldn't it make sense it if picked up the `project.name` field?

```toml
[project]
name = "sisl"

[tool.towncrier]
#package = "sisl"
#name = "sisl"
```
I need to uncomment one of the above two to get the correct name.

Seems redundant to double annotate it?
