### ISSUE TITLE
Inconsistent casing depending on `towncrier.name` / `towncrier.package` in the titles

### ISSUE THREAD

**Issue by zerothi** [twisted/towncrier#686]
When building the changelog I get different behaviour depending on whether I use `tool.towncrier.name` or `tool.towncrier.package`.

1. Using `package`
```toml
[tool.towncrier]
package = "sisl"
#name = "sisl"
```
and running `towncrier build ...` I get:
```shell
Sisl 0.15.3 Release Notes
*************************
...
```

2. Using `name`
```toml
[tool.towncrier]
#package = "sisl"
name = "sisl"
```
and running `towncrier build ...` I get:
```shell
sisl 0.15.3 Release Notes
*************************
...
```
all other options are the same.

Why is this? I couldn't find information about this discrepancy in the docs.
