### ISSUE TITLE
Adding options for fragments/types

### ISSUE THREAD

**Issue by zerothi** [twisted/towncrier#688]
The fragments currently only has 3 keys:

- `name`
- `check`
- `showcontent`

However, the format of several details of the fragment is controlled by some top-level keys.

- `issue_format`
- `all_bullets`
- possibly more

Would `towncrier` accept a PR where (at least the above two) are allowed in the fragments, but fallback to the global values?

My main motivation is that separate fragments can require special formatting in terms of issues.

**Comment by adiroiban** [comment]
Hi Nick, THanks for the report.

I am not sure what feature is requested here.

Can you provide a full example of input files and the expected output vs the actual output?

Cheers

**Comment by zerothi** [comment]
I could imagine something like this:
```toml
[tool.towncrier]
issue_format = ":issue:`{issue}`"

    [[tool.towncrier.type]]
    directory = "highlight"
    name = "Highlights"
    showcontent = true
    issue_format = ":pull:`{issue}`"

 ...
```
and now all fragments that are highlights, are outputting:
```
  (:pull:`865`)
```
while all other show:
```
  (:issue:`865`)
```
It allows some more customization, at very little confusion.

Sorry for not expanding anymore, I hope this is OK?
